version: "3.9"
services:
  app:
    container_name: golang_container
    environment:
      - user=${user}
      - password=${password}
      - dbname=${dbname}
      - host=${host}
      - PORT=${portdb}
    tty: true
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - app_docker

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "1234:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - app_docker

volumes:
  pg_data:

# Networks to be created to facilitate communication between containers
networks:
  app_docker:
    driver: bridge
